const description = "Final reporting table after all modeling is completed"

const columns = {
    "album_id" : "The Spotify ID for the album." ,
    "album_name" : "The name of the album. In case of an album takedown, the value may be an empty string." ,
    "album_popularity" : "The popularity of the album. The value will be between 0 and 100, with 100 being the most popular."  ,
    "album_type" : "The type of the album. Allowed values: album, single, compilation"  ,
    "artists" : "The artists who performed the track"  ,
    "artist_0" : "Main Artist"  ,
    "artist_1" : "Featuring Artist"  ,
    "artist_2" : "Featuring Artist" ,
    "artist_3" : "Featuring Artist"  ,
    "artist_4" : "Featuring Artist"  ,
    "artist_id" : "The Spotify ID for the artist."  ,
    "duration_sec" : "Track length in seconds"  ,
    'label' : "The label associated with the album."  ,
    'release_date' : "The date the album was first released."  ,
    'total_tracks' : "The number of tracks in the album."  ,
    'track_id' : "The Spotify ID for the track."  ,
    "track_name" : "Name of the track"  ,
    "track_number" : "The number of the track. If an album has several discs, the track number is the number on the specified disc."  ,
    "artist_genres" : "A list of the genres the artist is associated with. If not yet classified, the array is empty."  ,
    "artist_popularity" : "The popularity of the artist. The value will be between 0 and 100, with 100 being the most popular. The artist's popularity is calculated from the popularity of all the artist's tracks."  ,
    "followers" : "The total number of followers."  ,
    "name" : "Name of the Artist"  ,
    "genre_0" : "Main Genre"  ,
    "genre_1" : "Sub Genre"  ,
    "genre_2" : "Sub Genre" ,
    "genre_3" : "Sub Genre"  ,
    "genre_4" : "Sub Genre"  ,
    "acousticness" : "A confidence measure from 0.0 to 1.0 of whether the track is acoustic. 1.0 represents high confidence the track is acoustic."  ,
    "analysis_url" : "A URL to access the full audio analysis of this track. An access token is required to access this data."  ,
    "danceability" : "Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable."  ,
    "duration_ms" : "The duration of the track in milliseconds."  ,
    'energy' : "Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy."  ,
    "instrumentalness" : "Predicts whether a track contains no vocals. Ooh and aah sounds are treated as instrumental in this context. Rap or spoken word tracks are clearly vocal. The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content. Values above 0.5 are intended to represent instrumental tracks, but confidence is higher as the value approaches 1.0."  ,
    "key" : "The key the track is in. Integers map to pitches using standard Pitch Class notation. E.g. 0 = C, 1 = C♯/D♭, 2 = D, and so on. If no key was detected, the value is -1."  ,
    "liveness" : "Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live."  ,
    "loudness" : "The overall loudness of a track in decibels (dB). Loudness values are averaged across the entire track and are useful for comparing relative loudness of tracks. Loudness is the quality of a sound that is the primary psychological correlate of physical strength (amplitude). Values typically range between -60 and 0 db."  ,
    "mode" : "Mode indicates the modality (major or minor) of a track, the type of scale from which its melodic content is derived. Major is represented by 1 and minor is 0."  ,
    "speechiness" : "Speechiness detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value. Values above 0.66 describe tracks that are probably made entirely of spoken words. Values between 0.33 and 0.66 describe tracks that may contain both music and speech, either in sections or layered, including such cases as rap music. Values below 0.33 most likely represent music and other non-speech-like tracks.",
    "tempo" : "The overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration."  ,
    "time_signature" : "An estimated time signature. The time signature (meter) is a notational convention to specify how many beats are in each bar (or measure). The time signature ranges from 3 to 7 indicating time signatures of 3/4, to 7/4."  ,
    "track_href" : "A link to the Web API endpoint providing full details of the track."  ,
    "type" : "The object type."  ,
    "uri" : "The Spotify URI for the track."  ,
    "valence" : "A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry)."  ,
    "explicit" : "Whether or not the track has explicit lyrics ( true = yes it does; false = no it does not OR unknown)."  ,
    "track_popularity" : "The popularity of a track is a value between 0 and 100, with 100 being the most popular. The popularity is calculated by algorithm and is based, in the most part, on the total number of plays the track has had and how recent those plays are. Duplicate tracks (e.g. the same track from a single and an album) are rated independently. Artist and album popularity is derived mathematically from track popularity.",
    "release_year": "The year of the album/single release",
    "release_month" : "The month of the album/single release"
}

module.exports = {
    columns,
    description
}